import {test} from 'node:test';import assert from 'node:assert/strict';import {createGame,candy,step} from '../magnet-candy/physics.mjs';
function boot(){const g=createGame();g.mode='playing';g.spawn=999;return g;}
function advance(g,t){for(let i=0;i<t*120;i++)step(g,1/120,()=>.5);}
test('magnetic attraction and repulsion act in opposite directions within range',()=>{for(const p of [1,-1]){const g=boot();g.balls=[candy(250,300,0)];g.magnet={x:360,y:300,active:true};g.polarity=p;advance(g,.3);assert.ok(g.balls[0].vx*p>0);}const g=boot();g.balls=[candy(20,300,0)];g.magnet.active=true;advance(g,.1);assert.equal(g.balls[0].vx,0);});
test('matching jars score once and reward consecutive catches',()=>{const g=boot();for(let i=0;i<3;i++){g.balls=[candy(120,736,0)];step(g,.01);assert.equal(g.balls.length,0);}assert.equal(g.caught,3);assert.equal(g.score,375);assert.equal(g.combo,3);});
test('wrong jars and gaps cost a life, fifth miss ends the game',()=>{const g=boot();for(let i=0;i<5;i++){g.balls=[candy(i%2?240:360,736,0)];step(g,.01);}assert.equal(g.misses,5);assert.equal(g.mode,'ended');assert.equal(g.score,0);});
test('pause freezes time and physics, timeout ends round',()=>{const g=boot();g.mode='paused';const before=JSON.stringify(g);advance(g,1);assert.equal(JSON.stringify(g),before);g.mode='playing';g.time=.01;step(g,.02);assert.equal(g.mode,'ended');assert.equal(g.time,0);});
test('natural falling candy can reach its matching jar without a magnetic field',()=>{const g=boot();g.balls=[candy(600,0,2)];advance(g,10);assert.equal(g.caught,1);assert.equal(g.score,100);});
test('sustained magnetic input keeps positions finite and particles bounded',()=>{const g=boot();for(let i=0;i<10800;i++){if(i%180===0)g.balls.push(candy(100+i%500,0,i%3));g.magnet={x:360+250*Math.sin(i/100),y:400+300*Math.cos(i/130),active:true};g.polarity=i%300<150?1:-1;step(g,1/120,()=>.5);for(const b of g.balls)assert.ok([b.x,b.y,b.vx,b.vy].every(Number.isFinite));assert.ok(g.particles.length<120);}});
