import {W,H,levels,createGame,ripple,step} from './physics.mjs';
const $=id=>document.getElementById(id),canvas=$('water'),ctx=canvas.getContext('2d');let g=createGame(),last=0,aim={x:125,y:715},keyboard=false;
let records=[];try{const saved=JSON.parse(localStorage.getItem('ripple-post-best')||'[]');if(Array.isArray(saved))records=saved.map(n=>Number.isInteger(n)&&n>0?n:null);}catch{}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function update(){const count=g.lights.filter(l=>l.collected).length;$('lights').textContent=g.lights.map(l=>l.collected?'✦':'✧').join(' ');$('lights').setAttribute('aria-label',`已收集 ${count} 束萤火`);$('strokes').textContent=g.strokes;$('best').textContent=records[g.level]??'—';$('levelName').textContent=levels[g.level].name;document.querySelectorAll('[data-level]').forEach(b=>{const active=Number(b.dataset.level)===g.level;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('pause').textContent=g.mode==='paused'?'▷ 继续':'Ⅱ 暂停';$('pause').disabled=!['playing','paused'].includes(g.mode);$('hint').textContent=count===3?'萤火收齐了！把纸船送进金色月环。':`已收集 ${count}/3 束萤火 · 在船后方轻点，把它推向光。`;}
function overlay(title,message,button,caption='A LETTER TO THE MOON'){$('overlay').hidden=false;$('title').textContent=title;$('message').textContent=message;$('start').textContent=button;$('caption').textContent=caption;}
function startLevel(n){g=createGame(n);g.mode='playing';aim={x:g.boat.x,y:g.boat.y+65};$('overlay').hidden=true;update();canvas.focus({preventScroll:true});}
function pause(){if(g.mode==='playing'){g.mode='paused';overlay('让晚安，稍等一会。','航行已暂停，纸船会留在这里。','继续送信 ↗');}else if(g.mode==='paused'){g.mode='playing';$('overlay').hidden=true;}update();}
function win(){const previous=records[g.level];if(!previous||g.strokes<previous){records[g.level]=g.strokes;try{localStorage.setItem('ripple-post-best',JSON.stringify(records));}catch{}}
 overlay(g.level===2?'所有晚安，都已送达。':'月亮收到你的信了。',`用了 ${g.strokes} 圈涟漪，送来了三束光。${!previous||g.strokes<previous?' 这是你的新纪录。':' 再试试更少的涟漪？'}`,g.level===2?'再寄一轮 ↗':'寄出下一封 ↗','DELIVERED WITH A LITTLE LIGHT');update();}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function draw(){ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#1d494c');bg.addColorStop(1,'#102f39');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);const t=reduced?0:g.time;
 ctx.lineWidth=1;for(let i=0;i<17;i++){ctx.beginPath();const y=28+i*49;ctx.moveTo(0,y);ctx.bezierCurveTo(230,y+15*Math.sin(t*.3+i),450,y-25,720,y+5);ctx.strokeStyle='#a5d2bd0b';ctx.stroke();}
 for(let i=0;i<45;i++){const x=(i*137.5+31)%W,y=(i*97.3+26)%H;circle(x,y,1.1,'#cfe3bb'+(i%3===0?'66':'24'));}
 const d=g.dock,ready=g.lights.every(l=>l.collected);ctx.lineWidth=2;circle(d.x,d.y,48,null,ready?'#ecd293':'#ecd29355');circle(d.x,d.y,57,null,'#ecd29322');ctx.font='40px Georgia';ctx.fillStyle='#ecd293';ctx.textAlign='center';ctx.fillText('☾',d.x,d.y+12);ctx.font='11px Arial';ctx.fillStyle='#d5d3ab';ctx.fillText(ready?'月亮码头 · 可以靠岸':'月亮码头 · 等待萤火',d.x,d.y+78);
 for(const r of g.rocks){circle(r.x,r.y+10,r.r+9,'#082b3445');circle(r.x,r.y,r.r+9,null,'#aac3a323');circle(r.x,r.y,r.r,'#46635b');circle(r.x-8,r.y-8,r.r*.81,'#597065');ctx.strokeStyle='#9ba78155';ctx.beginPath();ctx.arc(r.x-5,r.y-4,r.r*.7,3.3,5.1);ctx.stroke();for(let i=0;i<3;i++){ctx.fillStyle='#99aa82';ctx.beginPath();ctx.ellipse(r.x+i*14-14,r.y+5-i*9,5,14,-.5+i*.5,0,7);ctx.fill();}}
 for(const l of g.lights){if(l.collected)continue;const glow=ctx.createRadialGradient(l.x,l.y,1,l.x,l.y,43);glow.addColorStop(0,'#efd68845');glow.addColorStop(1,'#efd68800');circle(l.x,l.y,43,glow);ctx.save();ctx.translate(l.x,l.y+Math.sin(t*2+l.x)*3);ctx.rotate(Math.PI/4);ctx.fillStyle='#f3d991';ctx.fillRect(-6,-6,12,12);ctx.restore();circle(l.x,l.y,22,null,'#f3d99135');}
 for(const w of g.waves){ctx.lineWidth=2;circle(w.x,w.y,w.r,null,`rgba(183,225,204,${.65*(1-w.r/230)})`);if(w.r>15){ctx.lineWidth=1;circle(w.x,w.y,w.r-14,null,`rgba(183,225,204,${.22*(1-w.r/230)})`);}}
 const b=g.boat;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.hypot(b.vx,b.vy)>8?Math.atan2(b.vy,b.vx)+Math.PI/2:0);ctx.fillStyle='#001e3644';ctx.beginPath();ctx.ellipse(0,10,24,13,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(23,18);ctx.lineTo(0,10);ctx.closePath();ctx.fillStyle='#f5e9c5';ctx.fill();ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(-23,18);ctx.lineTo(0,10);ctx.closePath();ctx.fillStyle='#c9d8c3';ctx.fill();ctx.beginPath();ctx.moveTo(-23,18);ctx.lineTo(0,10);ctx.lineTo(23,18);ctx.lineTo(0,25);ctx.closePath();ctx.fillStyle='#e4d7ad';ctx.fill();ctx.restore();
 if(g.mode==='ready'){ctx.setLineDash([4,7]);circle(170,718,27,null,'#e1d6a680');ctx.setLineDash([]);}if(g.mode==='playing'&&keyboard){ctx.lineWidth=1;circle(aim.x,aim.y,13,null,'#f2d89c');ctx.beginPath();ctx.moveTo(aim.x-20,aim.y);ctx.lineTo(aim.x+20,aim.y);ctx.moveTo(aim.x,aim.y-20);ctx.lineTo(aim.x,aim.y+20);ctx.stroke();}
}
function resize(){const dpr=Math.min(devicePixelRatio||1,2),width=canvas.getBoundingClientRect().width;canvas.width=Math.round(width*dpr);canvas.height=Math.round(width*H/W*dpr);draw();}
canvas.addEventListener('pointerdown',e=>{if(g.mode!=='playing')return;e.preventDefault();keyboard=false;canvas.focus({preventScroll:true});const r=canvas.getBoundingClientRect();ripple(g,(e.clientX-r.left)/r.width*W,(e.clientY-r.top)/r.height*H);update();});
$('start').onclick=()=>{if(g.mode==='paused'){pause();canvas.focus({preventScroll:true});}else startLevel(g.mode==='won'?(g.level+1)%levels.length:g.level);};$('pause').onclick=pause;$('restart').onclick=()=>startLevel(g.level);document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>startLevel(Number(b.dataset.level)));
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLElement&&['BUTTON','A'].includes(e.target.tagName))return;if(e.code==='KeyP'&&!e.repeat){pause();return;}if(e.code==='KeyR'&&!e.repeat){startLevel(g.level);return;}if(g.mode!=='playing')return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code)){e.preventDefault();keyboard=true;if(e.code==='Space'){if(!e.repeat)ripple(g,aim.x,aim.y);}else{aim.x=Math.max(0,Math.min(W,aim.x+(e.code==='ArrowLeft'?-15:e.code==='ArrowRight'?15:0)));aim.y=Math.max(0,Math.min(H,aim.y+(e.code==='ArrowUp'?-15:e.code==='ArrowDown'?15:0)));}update();}});
window.addEventListener('blur',()=>{if(g.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.mode==='playing')pause();});
function frame(now){const dt=Math.min((now-last)/1000||0,.05);last=now;const before=g.mode,lights=g.lights.filter(l=>l.collected).length;for(let n=0;n<4;n++)step(g,dt/4);if(before==='playing'&&g.mode==='won')win();else if(lights!==g.lights.filter(l=>l.collected).length)update();draw();requestAnimationFrame(frame);}
new ResizeObserver(resize).observe(canvas);update();resize();requestAnimationFrame(frame);
