import {W,H,clamp,createGame,launch,jet,step,bumpers,rails} from './physics.mjs';
const $=id=>document.getElementById(id),canvas=$('table'),ctx=canvas.getContext('2d');let g=createGame(),best=0,last=0,soundOn=false,audio=null,keys=new Set(),held={left:new Set(),right:new Set()},viewScale=1;
try{best=Number(localStorage.getItem('aqua-pinball-best'))||0}catch{}
function resize(){const r=canvas.getBoundingClientRect();viewScale=r.width*Math.min(devicePixelRatio||1,2)/W;canvas.width=Math.round(W*viewScale);canvas.height=Math.round(H*viewScale)}new ResizeObserver(resize).observe(canvas);
function tone(freq){if(!soundOn)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const osc=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime;osc.connect(gain);gain.connect(audio.destination);osc.frequency.setValueAtTime(freq,t);osc.frequency.exponentialRampToValueAtTime(freq*.55,t+.2);gain.gain.setValueAtTime(.045,t);gain.gain.exponentialRampToValueAtTime(.001,t+.22);osc.start();osc.stop(t+.23)}catch{}}
function clearInput(){keys.clear();held.left.clear();held.right.clear()}
function save(){if(g.score>best){best=g.score;try{localStorage.setItem('aqua-pinball-best',best)}catch{}}}
function start(){g=createGame();g.mode='playing';clearInput();$('overlay').hidden=true;launch(g);canvas.focus({preventScroll:true});tone(300);update()}
function show(title,body,button){$('title').textContent=title;$('message').textContent=body;$('start').textContent=button;$('overlay').hidden=false}
function pause(){if(g.mode==='playing'){g.mode='paused';clearInput();show('水花，稍后继续。','水团已静止，准备好再接着弹。','继续弹水 ↗')}else if(g.mode==='paused'){g.mode='playing';$('overlay').hidden=true}update()}
$('quick').onclick=()=>{if(!g.balls.length){if(launch(g))tone(300)}else if(jet(g))tone(160)};
$('start').onclick=()=>g.mode==='paused'?pause():start();$('restart').onclick=start;$('pause').onclick=pause;$('launch').onclick=()=>{if(launch(g))tone(300)};$('jet').onclick=()=>{if(jet(g))tone(160)};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'♪ 音效开':'♪ 音效关';$('sound').setAttribute('aria-pressed',soundOn);tone(400)};
for(const side of ['left','right']){const el=$(side);el.onpointerdown=e=>{if(g.mode!=='playing')return;e.preventDefault();el.setPointerCapture(e.pointerId);held[side].add(e.pointerId);tone(160)};for(const name of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(name,e=>held[side].delete(e.pointerId))}
canvas.onpointerdown=e=>{if(g.mode!=='playing')return;canvas.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect(),side=e.clientX-r.left<r.width/2?'left':'right';held[side].add(e.pointerId)};
for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>{held.left.delete(e.pointerId);held.right.delete(e.pointerId)});
window.addEventListener('keydown',e=>{if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='KeyP'){pause();return}if(g.mode!=='playing')return;keys.add(e.code);if(e.code==='Space'&&launch(g))tone(300);if(e.code==='KeyJ'&&jet(g))tone(160)});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();if(g.mode==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.mode==='playing')pause()});
function controls(){return {left:held.left.size>0||keys.has('KeyA')||keys.has('ArrowLeft'),right:held.right.size>0||keys.has('KeyD')||keys.has('ArrowRight')}}
function update(){const c=controls();$('quick').disabled=g.mode!=='playing'||(g.balls.length?(g.jet>0||!g.balls.some(b=>!b.launching)):!g.stock);$('quick').innerHTML=g.balls.length?(g.jet>0?`≋ ${Math.ceil(g.jet)}s<small>喷流冷却</small>`:'≋ 喷流<small>向上托起</small>'):'↑ 发射<small>下一滴水</small>'; $('score').textContent=String(g.score).padStart(4,'0');$('best').textContent=best;$('cups').textContent=g.cups;$('combo').textContent=g.combo>1?`连续碰撞 ×${g.combo} · ${Math.min(g.combo,5)} 倍得分`:'每一次碰撞，都值得期待。';$('stock').textContent=Array.from({length:5},(_,i)=>i<g.stock?'●':'○').join(' ');$('stockLabel').textContent=g.stock+' / 5';$('hint').textContent=g.balls.length?`${g.balls.length} 滴水正在台面上，全部落空后可再发射。`:g.stock?'点击发射，让下一滴水出发。':'储水已用完，这一局完成。';$('status').textContent=g.mode==='paused'?'水面静止':g.balls.length?`${g.balls.length} DROPS IN PLAY`:g.mode==='ended'?'本局完成':'等待发射';$('launch').disabled=g.mode!=='playing'||g.balls.length>0||!g.stock;$('jet').disabled=g.mode!=='playing'||g.jet>0||!g.balls.some(b=>!b.launching);$('jetLabel').textContent=g.jet>0?`${g.jet.toFixed(1)} 秒后恢复`:'救回下落的水团 · J';$('pause').disabled=!['playing','paused'].includes(g.mode);$('pause').textContent=g.mode==='paused'?'▷ 继续':'Ⅱ 暂停';$('left').classList.toggle('active',c.left);$('right').classList.toggle('active',c.right)}
function circle(x,y,r,fill,stroke,width=1){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}}
function line(a,color,width){ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(a[2],a[3]);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.stroke()}
function label(text,x,y,size=12,color='#8ca69b'){ctx.font=`${size}px Arial, "PingFang SC", sans-serif`;ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,x,y)}
function drawDrop(b,time){const speed=Math.hypot(b.vx,b.vy),stretch=1+Math.min(.38,speed/3000);ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.squash>.1?b.angle:Math.atan2(b.vy,b.vx));ctx.scale((1-b.squash)*stretch,1/((1-b.squash)*Math.sqrt(stretch)));ctx.beginPath();for(let i=0;i<=40;i++){const a=i/40*Math.PI*2,r=b.r*(1+.065*Math.sin(a*3+time*9)+.035*Math.cos(a*5-time*8));i?ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r):ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();const gr=ctx.createRadialGradient(-b.r*.3,-b.r*.4,0,0,0,b.r*1.2);gr.addColorStop(0,'#c8f8ec');gr.addColorStop(.28,'#81d4ce');gr.addColorStop(.7,'#379da9');gr.addColorStop(1,'#21778c');ctx.fillStyle=gr;ctx.shadowColor='#4bafbe66';ctx.shadowBlur=12;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#1f879a';ctx.lineWidth=.8;ctx.stroke();ctx.beginPath();ctx.ellipse(-b.r*.23,-b.r*.4,b.r*.35,b.r*.14,-.3,0,Math.PI*2);ctx.fillStyle='#ffffffba';ctx.fill();ctx.restore()}
function draw(){ctx.setTransform(viewScale,0,0,viewScale,0,0);ctx.clearRect(0,0,W,H);const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#f7f8ee');grad.addColorStop(1,'#e5f0e9');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
 for(let y=35;y<H;y+=25)for(let x=25;x<W;x+=25)circle(x,y,.65,'#a5bca32c');
 // Nested racetrack lines and wave patterns sit underneath all game colliders.
 ctx.strokeStyle='#c5d9c8';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(28,30,544,820,100);ctx.stroke();ctx.strokeStyle='#d6e2cd';ctx.beginPath();ctx.roundRect(36,38,528,804,94);ctx.stroke();
 for(let k=0;k<4;k++){ctx.beginPath();for(let x=90;x<=510;x+=8){const y=520+k*11+Math.sin(x*.022+k*.6)*14; x===90?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle='#a6c9b730';ctx.stroke()}
 line([523,785,523,205],'#85b7aa22',35);label('↑',523,685,18,'#8aafa0');label('THE SPLASH CLUB',300,244,12,'#8fab9d');label('碰碰运气，也接住快乐',300,263,10,'#adc0ae');
 // Gold catch cup; its open mouth is the scoring gate.
 ctx.fillStyle='#e8cf8d33';ctx.beginPath();ctx.roundRect(247,150,106,51,[0,0,20,20]);ctx.fill();const fill=Math.min(g.cups,5)/5*31;ctx.fillStyle='#dfb66988';ctx.fillRect(253,190-fill,94,fill);line([246,153,246,191],'#c7a45d',5);line([354,153,354,191],'#c7a45d',5);ctx.beginPath();ctx.moveTo(246,191);ctx.quadraticCurveTo(300,218,354,191);ctx.strokeStyle='#c7a45d';ctx.lineWidth=5;ctx.stroke();line([255,144,345,144],'#d3b57755',1);label('CATCH THE DROP',300,118,10,'#bda367');label('+500',300,179,14,'#b18d4e');
 for(let i=0;i<bumpers.length;i++){const b=bumpers[i],flash=g.bumperFlash[i];circle(b.x,b.y+5,b.r+10,'#5a8d7811');circle(b.x,b.y,b.r+13,null,'#b3cbbb',1);circle(b.x,b.y,b.r+6,'#eef4e1','#cee1c7',2);const bg=ctx.createRadialGradient(b.x-12,b.y-13,3,b.x,b.y,b.r);bg.addColorStop(0,flash?'#f7e5ac':'#dfefc7');bg.addColorStop(1,flash?'#dac280':'#accda6');circle(b.x,b.y,b.r,bg,'#91b793',2);circle(b.x,b.y,b.r-7,null,'#ffffff99',1);label(i===2?'✦':'✳',b.x,b.y+9,i===2?29:25,'#6a9a80');if(flash){circle(b.x,b.y,b.r+12+(1-flash/.32)*25,null,`rgba(119,178,148,${flash*2})`,2)}}
 for(const a of rails.slice(0,9)){line([a[0],a[1]+3,a[2],a[3]+3],'#9bb6a333',14);line(a,'#91bbaa',10);line([a[0]-1,a[1]-2,a[2]-1,a[3]-2],'#e8f4dd',3)}
 // The two slingshot lanes point back toward the flippers.
 label('↗',133,598,22,'#90b4a0');label('↖',467,598,22,'#90b4a0');label('KEEP IT FLOWING',300,630,11,'#a1b6a2');
 if(g.jet>6){for(let i=0;i<9;i++){let x=110+i*47,y=800-(g.time*420+i*40)%350;line([x,y,x,y-55],'#6ebfbe55',3)}}
 for(const f of g.flippers){const dx=Math.cos(f.a)*128,dy=Math.sin(f.a)*128;line([f.x,f.y+4,f.x+dx,f.y+dy+4],'#678f782c',30);line([f.x,f.y,f.x+dx,f.y+dy],'#3f8582',24);line([f.x,f.y-4,f.x+dx,f.y+dy-4],'#a8dbca',6);circle(f.x,f.y,16,'#d9e9ce','#6c9e8a',2);circle(f.x,f.y,5,'#65998b')}
 label('↓  下一滴水，下一次机会  ↓',300,862,10,'#9cb5a5');
 if(!g.balls.length&&g.mode!=='ended'){drawDrop({x:501,y:770,r:19,vx:0,vy:0,squash:0},g.time);label('↑',501,824,22,'#80b1a1')}
 for(const b of g.balls){for(let i=b.trail.length-1;i>=0;i--){const p=b.trail[i];circle(p.x,p.y,b.r*(1-i/15),`rgba(61,166,182,${.018*(12-i)})`)}drawDrop(b,g.time)}
 for(const e of g.effects){ctx.globalAlpha=clamp(e.t*2,0,1);if(e.type==='splash'){for(let i=0;i<10;i++){const a=i*Math.PI*.2+e.seed,r=(.6-e.t)*170;circle(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r+(.6-e.t)**2*90,1.5+e.t*3,e.color)}circle(e.x,e.y,(.6-e.t)*80+12,null,e.color,1)}label(e.text,e.x,e.y-25-(.6-e.t)*50,17,e.color||'#328e96');ctx.globalAlpha=1}
}
function frame(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;const oldHits=g.hits,oldCups=g.cups,mode=g.mode;step(g,dt,controls());if(g.hits>oldHits)tone(450+g.combo*45);if(g.cups>oldCups)tone(900);save();if(g.mode==='ended'&&mode!=='ended'){clearInput();show('这一局，水花很漂亮。',`累计 ${g.score} 分 · 入杯 ${g.cups} 次\n撞击机关 ${g.hits} 次，再来创造新纪录。`,'再弹一局 ↗')}draw();update();requestAnimationFrame(frame)}
window.aquaPinball={getState:()=>({mode:g.mode,score:g.score,stock:g.stock,cups:g.cups,hits:g.hits,balls:g.balls.map(({trail,...b})=>({...b})),jet:g.jet})};resize();update();requestAnimationFrame(frame);
