import {W,H,colors,jars,createGame,step} from './physics.mjs';
const $=id=>document.getElementById(id),canvas=$('field'),ctx=canvas.getContext('2d'),keys=new Set();let g=createGame(),last=0,pointer=null,best=0;
try{best=Math.max(0,Number(localStorage.getItem('candy-field-best'))||0);}catch{}
function release(){keys.clear();g.magnet.active=false;pointer=null;}
function update(){ $('score').textContent=String(g.score).padStart(4,'0');$('time').textContent=Math.ceil(g.time)+'s';$('best').textContent=best;$('lives').textContent=Array.from({length:5},(_,i)=>i<5-g.misses?'●':'○').join(' ');$('caught').textContent=`已装罐 ${g.caught} 颗 · 失误 ${g.misses}/5 次`;$('combo').textContent=g.combo>1?`${g.combo} 连续入罐 · 下颗最高 +${100+Math.min(g.combo,9)*25} 分`:g.caught?'接住了！继续把甜蜜送回家。':'第一颗甜，正在路上。';$('next').textContent=`下一颗 · ${jars[g.next].label} ${jars[g.next].symbol}`;$('pause').disabled=!['playing','paused'].includes(g.mode);$('pause').textContent=g.mode==='paused'?'▷ 继续':'Ⅱ 暂停';for(const [id,p] of [['attract',1],['repel',-1]]){$(id).classList.toggle('selected',g.polarity===p);$(id).setAttribute('aria-pressed',String(g.polarity===p));}}
function show(title,message,button){$('title').textContent=title;$('message').textContent=message;$('start').textContent=button;$('overlay').hidden=false;}
function start(){release();g=createGame();g.mode='playing';$('overlay').hidden=true;update();canvas.focus({preventScroll:true});}
function pause(){if(g.mode==='playing'){g.mode='paused';release();show('甜蜜暂停一下。','糖球会留在这里，准备好再继续。','继续分糖 ↗');}else if(g.mode==='paused'){g.mode='playing';$('overlay').hidden=true;canvas.focus({preventScroll:true});}update();}
function finish(){release();if(g.score>best){best=g.score;try{localStorage.setItem('candy-field-best',String(best));}catch{}}show(g.misses>=5?'糖纸用完啦。':'今日甜蜜，分配完成。',`成功装罐 ${g.caught} 颗，获得 ${g.score} 分。再来一次，试试更长的连续入罐！`,'再开一班 ↗');update();}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function symbol(type,x,y,size,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();if(type===0)ctx.arc(x,y,size*.7,0,Math.PI*2);else if(type===1){ctx.moveTo(x,y-size);ctx.lineTo(x+size,y);ctx.lineTo(x,y+size);ctx.lineTo(x-size,y);ctx.closePath();}else{ctx.moveTo(x,y-size);ctx.lineTo(x+size,y+size*.7);ctx.lineTo(x-size,y+size*.7);ctx.closePath();}ctx.stroke();}
function draw(){ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);ctx.fillStyle='#e9ebdf';ctx.fillRect(0,0,W,H);ctx.fillStyle='#cbd4c2';for(let x=24;x<W;x+=32)for(let y=24;y<700;y+=32){circle(x,y,.85,'#cbd4c2');}ctx.fillStyle='#d9dfcd';ctx.fillRect(0,0,W,8);
 ctx.setLineDash([4,9]);ctx.strokeStyle='#a9b49c55';ctx.lineWidth=1;for(const x of [240,480]){ctx.beginPath();ctx.moveTo(x,650);ctx.lineTo(x,H);ctx.stroke();}ctx.setLineDash([]);
 for(const j of jars){ctx.fillStyle=colors[j.color]+'30';ctx.beginPath();ctx.roundRect(j.x-83,731,166,81,[4,4,22,22]);ctx.fill();ctx.strokeStyle=colors[j.color];ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(j.x-83,731,166,81,[4,4,22,22]);ctx.stroke();ctx.fillStyle=colors[j.color];ctx.fillRect(j.x-90,727,180,9);symbol(j.color,j.x-30,770,10,'#46554a');ctx.fillStyle='#46554a';ctx.font='15px Arial';ctx.textAlign='left';ctx.fillText(j.label,j.x-10,776);}
 const m=g.magnet;if(g.mode==='playing'){const color=g.polarity===1?'#618b77':'#ca806f';ctx.lineWidth=1;if(m.active){const grad=ctx.createRadialGradient(m.x,m.y,5,m.x,m.y,245);grad.addColorStop(0,color+'30');grad.addColorStop(1,color+'00');circle(m.x,m.y,245,grad);ctx.setLineDash([3,8]);circle(m.x,m.y,245,null,color+'45');ctx.setLineDash([]);for(const r of [55,115,175])circle(m.x,m.y,r,null,color+'25');}circle(m.x,m.y,24,m.active?color:color+'22',color);ctx.textAlign='center';ctx.font='28px Arial';ctx.fillStyle=m.active?'#fff8e5':color;ctx.fillText(g.polarity===1?'+':'−',m.x,m.y+9);ctx.font='11px Arial';ctx.fillStyle='#677966';ctx.fillText(m.active?(g.polarity===1?'吸引中':'排斥中'):'按住开启磁场',m.x,Math.min(700,m.y+46));}
 for(const b of g.balls){ctx.save();ctx.translate(b.x,b.y);const stretch=Math.min(.15,Math.hypot(b.vx,b.vy)/1700);ctx.rotate(Math.atan2(b.vy,b.vx)-Math.PI/2);ctx.scale(1-stretch,1+stretch);circle(3,7,b.r,'#45683c12');const grad=ctx.createRadialGradient(-7,-9,1,0,0,28);grad.addColorStop(0,'#fff7e6');grad.addColorStop(.35,colors[b.color]);grad.addColorStop(1,colors[b.color]);circle(0,0,b.r,grad);ctx.restore();symbol(b.color,b.x,b.y,7,'#354e46');}
 for(const p of g.particles){ctx.globalAlpha=Math.max(0,p.life/.7);circle(p.x,p.y,3,p.color);}ctx.globalAlpha=1;
 if(g.mode==='ready'){for(const [x,y,c] of [[120,140,0],[380,255,2],[560,110,1],[210,410,1],[560,520,0]]){circle(x,y,23,colors[c]);symbol(c,x,y,7,'#354e46');}}
}
function resize(){const width=canvas.getBoundingClientRect().width,dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(width*H/W*dpr);draw();}
function locate(e){const r=canvas.getBoundingClientRect();g.magnet.x=Math.max(0,Math.min(W,(e.clientX-r.left)/r.width*W));g.magnet.y=Math.max(0,Math.min(H,(e.clientY-r.top)/r.height*H));}
canvas.addEventListener('pointerdown',e=>{if(g.mode!=='playing'||pointer!==null)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);locate(e);g.magnet.active=true;canvas.focus({preventScroll:true});});canvas.addEventListener('pointermove',e=>{if(g.mode==='playing'&&(pointer===e.pointerId||(pointer===null&&e.pointerType==='mouse')))locate(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(e.pointerId===pointer){pointer=null;g.magnet.active=keys.has('Space');}});
function polarity(p){g.polarity=p;update();}for(const [id,p] of [['attract',1],['repel',-1]]){$(id).addEventListener('pointerdown',e=>{e.preventDefault();polarity(p);});$(id).onclick=()=>polarity(p);}
$('start').onclick=()=>g.mode==='paused'?pause():start();$('restart').onclick=start;$('pause').onclick=pause;
window.addEventListener('keydown',e=>{if(['BUTTON','A'].includes(e.target?.tagName))return;if(e.code==='KeyP'&&!e.repeat){pause();return;}if(g.mode!=='playing')return;if(e.code==='KeyX'&&!e.repeat)polarity(-g.polarity);if(['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)){e.preventDefault();keys.add(e.code);if(e.code==='Space')g.magnet.active=true;}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space'&&pointer===null)g.magnet.active=false;});window.addEventListener('blur',()=>{if(g.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.mode==='playing')pause();});
function frame(now){const dt=Math.min((now-last)/1000||0,.05);last=now;if(g.mode==='playing'){g.magnet.x=Math.max(0,Math.min(W,g.magnet.x+((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0))*360*dt));g.magnet.y=Math.max(0,Math.min(H,g.magnet.y+((keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0))*360*dt));for(let i=0;i<4;i++)step(g,dt/4);if(g.mode==='ended')finish();update();}draw();requestAnimationFrame(frame);}new ResizeObserver(resize).observe(canvas);update();resize();requestAnimationFrame(frame);
